version: '3.8' # Or a suitable version for your Docker installation
services:
  ibkrpnl:
    build:
      context: . # Path to your Dockerfile
      dockerfile: Dockerfile
    container_name: my_ibkr_pnl
    network_mode: host
    volumes:
      - "/home/baichen/ibkr_docker_daily:/app/data"
    command: ["python", "runPnL.py"] # This is where you define the CMD
